name: code_checker
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install flake8 bandit black
      - run: black --check .
      - run: flake8 . --max-line-length=200
      - run: bandit --recursive .